// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

/**
 * breaking command - Apply backward compatibility rules to detect breaking changes
 */

import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import { RulesEngine } from '../lib/rules-engine.js';

export const breakingCommand = new Command('breaking')
  .description('Spot non-backward compatible changes from a structural diff')
  .requiredOption('--diff <file>', 'Structural diff file from \'diff\' command')
  .option('--rules <file>', 'Custom compatibility rules YAML file (default: built-in breaking-changes.yaml)', undefined)
  .option('--output <file>', 'Diff-breaking output file (default: stdout)')
  .option('--suggest-version', 'Display semantic versioning recommendation', false)
  .option('--quiet', 'Suppress informational messages', false)
  .configureHelp({
    formatHelp: (cmd, helper) => {
      return `Usage: ${helper.commandUsage(cmd)}

${helper.commandDescription(cmd)}

Applies compatibility rules to identify which changes are breaking vs. compatible.
Requires a structural diff file generated by the 'diff' command.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INPUT FILE (Required):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  --diff <file>                 Structural diff file from 'diff' command
                                (e.g., diff.json)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RULES OPTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  --rules <file>                Custom compatibility rules YAML file
                                (default: built-in breaking-changes.yaml)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT OPTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  --output <file>               Diff-breaking output file (default: stdout)
                                Recommended: diff-breaking.json
  --suggest-version             Display semantic versioning recommendation
  --quiet                       Suppress informational messages (default: false)
  -h, --help                    Display help for command

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXAMPLES:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Analyze with built-in rules
  $ mcpcontract breaking \\
      --diff diff.json \\
      --output diff-breaking.json

  # Use custom compatibility rules
  $ mcpcontract breaking \\
      --diff diff.json \\
      --rules my-rules.yaml \\
      --output diff-breaking.json

  # Show version recommendation
  $ mcpcontract breaking \\
      --diff diff.json \\
      --suggest-version \\
      --output diff-breaking.json

  # Generate changelog highlighting breaking changes
  $ mcpcontract changelog --analysis diff-breaking.json --output CHANGELOG.md
`;
    }
  })
  .action(async (options) => {
    try {
      const { diff: diffFile, rules: customRules, output, suggestVersion, quiet } = options;

      if (!quiet) {
        console.error(`🔍 Analyzing ${diffFile} for breaking changes...`);
      }

      // Check diff file exists
      if (!fs.existsSync(diffFile)) {
        console.error(`❌ Error: Diff file not found: ${diffFile}`);
        process.exit(2);
      }

      // Load diff
      const diffContent = fs.readFileSync(diffFile, 'utf-8');
      let diffData: any;
      
      try {
        diffData = JSON.parse(diffContent);
      } catch (error) {
        console.error(`❌ Error parsing diff file: ${(error as Error).message}`);
        process.exit(2);
      }

      // Determine rules file
      let rulesPath: string;
      if (customRules) {
        rulesPath = customRules;
        if (!fs.existsSync(rulesPath)) {
          console.error(`❌ Error: Rules file not found: ${rulesPath}`);
          process.exit(2);
        }
      } else {
        // Use built-in rules
        const moduleDir = path.dirname(new URL(import.meta.url).pathname);
        rulesPath = path.join(moduleDir, '../../rules/breaking-changes.yaml');
        
        if (!fs.existsSync(rulesPath)) {
          console.error(`❌ Error: Default rules file not found at ${rulesPath}`);
          process.exit(2);
        }
      }

      if (!quiet && customRules) {
        console.error(`📋 Using custom rules: ${rulesPath}`);
      } else if (!quiet) {
        console.error(`📋 Using default rules: rules/breaking-changes.yaml`);
      }

      // Create rules engine and analyze
      const engine = new RulesEngine(rulesPath);
      const analysis = engine.analyze(diffData, diffFile, rulesPath);

      // Output result
      const analysisJson = JSON.stringify(analysis, null, 2);

      if (output) {
        fs.writeFileSync(output, analysisJson, 'utf-8');
        if (!quiet) {
          console.error(`\n✅ Analysis written to ${output}`);
          console.error(`   Status: ${analysis.summary.status}`);
          console.error(`   Total changes: ${analysis.summary.totalChanges}`);
          console.error(`   Breaking changes: ${analysis.summary.breakingChanges} (${analysis.categorization.breaking.length} categorized)`);
          console.error(`   Compatible changes: ${analysis.summary.compatibleChanges}`);
          
          // Show categorization summary
          console.error(`\n📊 Change Categorization:`);
          console.error(`   ⚠️  Breaking: ${analysis.categorization.breaking.length}`);
          console.error(`   ✨ New: ${analysis.categorization.new.length}`);
          console.error(`   🔄 Updates: ${analysis.categorization.updates.length}`);
          console.error(`   🗑️  Deleted: ${analysis.categorization.deleted.length}`);
          
          // Show version suggestion if requested
          if (suggestVersion) {
            console.error(`\n🔢 Semantic Versioning Recommendation:`);
            console.error(`   Recommended bump: ${analysis.versioningSuggestion.recommendedBump.toUpperCase()}`);
            console.error(`   Reason: ${analysis.versioningSuggestion.reason}`);
            
            if (analysis.metadata.old.version && analysis.versioningSuggestion.suggestedVersion) {
              console.error(`   Version: ${analysis.metadata.old.version} → ${analysis.versioningSuggestion.suggestedVersion}`);
            }
          }
        }
      } else {
        // Output to stdout
        console.log(analysisJson);
      }

      // Exit with appropriate code
      process.exit(analysis.summary.exitCode);
    } catch (error) {
      console.error(`❌ Unexpected error: ${(error as Error).message}`);
      if ((error as Error).stack) {
        console.error((error as Error).stack);
      }
      process.exit(2);
    }
  });
